-- Configurable scoring rules for live quiz speed-based rating.
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS live_score_025 NUMERIC(8,2) NOT NULL DEFAULT 2.00;
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS live_score_050 NUMERIC(8,2) NOT NULL DEFAULT 1.50;
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS live_score_075 NUMERIC(8,2) NOT NULL DEFAULT 1.25;
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS live_score_100 NUMERIC(8,2) NOT NULL DEFAULT 1.00;
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS live_score_wrong NUMERIC(8,2) NOT NULL DEFAULT -0.50;
