import { useEffect, useMemo, useState } from "react";
import { Clock3, Medal, Users, ArrowRight, X, CheckCircle2, CircleX, CircleHelp } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import StudentLayout from "../../components/student/StudentLayout";
import LoadingSpinner from "../../components/common/LoadingSpinner";
import { getLiveQuizzes, getLiveQuizStats, getLiveQuizResult, getLiveRanking, getLiveRegistration, registerLiveQuiz } from "../../api/liveQuiz.api";

const formatCountdown = (value, now) => { const diff = new Date(value).getTime() - now; if (!Number.isFinite(diff)) return "—"; if (diff <= 0) return "Live now"; const total=Math.floor(diff/1000),days=Math.floor(total/86400),hours=Math.floor((total%86400)/3600),minutes=Math.floor((total%3600)/60),seconds=total%60; if(days)return `${days}d ${hours}h ${minutes}m`; if(hours)return `${hours}h ${minutes}m ${String(seconds).padStart(2,"0")}s`; return `${minutes}m ${String(seconds).padStart(2,"0")}s`; };
const formatDate = (value) => value ? `${new Intl.DateTimeFormat("en-IN", { timeZone:"Asia/Kolkata", day:"2-digit", month:"short", year:"numeric", hour:"2-digit", minute:"2-digit", hour12:true }).format(new Date(value))} IST` : "—";

function Avatar({ user, size="h-11 w-11" }) { const initials=(user?.name||"Student").trim().split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase(); if(user?.avatar_url)return <img src={user.avatar_url} alt="" className={`${size} rounded-full object-cover border border-slate-200`}/>; return <div className={`${size} grid place-items-center rounded-full bg-slate-100 text-sm text-slate-600`}>{initials}</div>; }
function RankRow({ item }) { return <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-3 py-3 sm:px-4"><span className="w-7 text-center text-sm text-slate-400">{item.rank}</span><Avatar user={item}/><div className="min-w-0 flex-1"><p className="truncate text-sm text-slate-900">{item.name}</p><p className="mt-0.5 text-xs text-slate-400">{item.attended} attended</p></div><div className="text-right"><p className="text-sm tabular-nums text-slate-900">{Number(item.total_rating||0).toFixed(2)}</p><p className="text-[11px] text-slate-400">rating</p></div></div>; }
function PastContestCard({ quiz, onOpen }) { const attended=Number(quiz.my_attempt_count||0)>0; return <button type="button" onClick={()=>onOpen(quiz)} className="card w-full text-left transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] uppercase tracking-wide text-slate-500">Live quiz</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] uppercase tracking-wide text-emerald-700">Ended</span>{attended&&<span className="rounded-full bg-indigo-50 px-2.5 py-1 text-[10px] uppercase tracking-wide text-indigo-700">Attended</span>}</div><h3 className="mt-3 truncate text-base text-slate-900">{quiz.title}</h3><p className="mt-1 text-xs text-slate-500">{formatDate(quiz.live_start_at)}</p></div>{attended&&<div className="shrink-0 rounded-xl bg-slate-50 px-3 py-2 text-right"><p className="text-[10px] uppercase tracking-wide text-slate-400">Your rating</p><p className="mt-1 text-sm tabular-nums text-slate-900">{Number(quiz.my_rating||0).toFixed(2)}</p></div>}</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-slate-50 p-2"><p className="text-[10px] text-slate-400">Questions</p><p className="mt-1 text-sm text-slate-700">{quiz.question_count||0}</p></div><div className="rounded-lg bg-slate-50 p-2"><p className="text-[10px] text-slate-400">Participants</p><p className="mt-1 text-sm text-slate-700">{quiz.attempt_count||0}</p></div><div className="rounded-lg bg-slate-50 p-2"><p className="text-[10px] text-slate-400">Your rank</p><p className="mt-1 text-sm text-slate-700">{attended&&quiz.my_rank?`#${quiz.my_rank}`:"—"}</p></div></div><div className="mt-4 inline-flex items-center gap-1 text-xs text-indigo-600">View event result <ArrowRight size={13}/></div></button>; }
const ResultMetric=({label,value,tone="neutral",icon:Icon})=>{const toneClass=tone==="good"?"bg-emerald-50 text-emerald-700":tone==="bad"?"bg-rose-50 text-rose-700":tone==="warn"?"bg-amber-50 text-amber-700":"bg-slate-50 text-slate-700";return <div className="rounded-xl border border-slate-100 bg-white p-3 sm:p-4"><div className="flex items-center justify-between gap-2"><p className="text-xs text-slate-500">{label}</p>{Icon&&<span className={`grid h-7 w-7 place-items-center rounded-lg ${toneClass}`}><Icon size={14}/></span>}</div><p className="mt-2 text-xl tabular-nums text-slate-900">{value}</p></div>;};

export default function LiveQuizzes(){
 const [quizzes,setQuizzes]=useState([]),[stats,setStats]=useState({}),[ranking,setRanking]=useState([]),[registrations,setRegistrations]=useState({}),[selected,setSelected]=useState(null),[pastTab,setPastTab]=useState("all"),[loading,setLoading]=useState(true),[now,setNow]=useState(Date.now());
 const navigate=useNavigate(),location=useLocation();
 const load=async()=>{try{const [quizResponse,statsResponse,rankingResponse]=await Promise.all([getLiveQuizzes(),getLiveQuizStats(),getLiveRanking()]);const list=quizResponse.data.quizzes||[];setQuizzes(list);setStats(statsResponse.data.stats||{});setRanking(rankingResponse.data.ranking||[]);const upcoming=list.filter(q=>q.live_state==="upcoming");const results=await Promise.all(upcoming.map(async q=>{try{const r=await getLiveRegistration(q.id);return[q.id,r.data.registered];}catch{return[q.id,false];}}));setRegistrations(Object.fromEntries(results));}catch(e){console.error(e);}finally{setLoading(false);}};
 useEffect(()=>{load();const refresh=setInterval(load,15000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(refresh);clearInterval(clock);};},[]);
 const liveNow=useMemo(()=>quizzes.filter(q=>q.live_state==="live"),[quizzes]),upcoming=useMemo(()=>quizzes.filter(q=>q.live_state==="upcoming"),[quizzes]),previous=useMemo(()=>quizzes.filter(q=>q.live_state==="completed"),[quizzes]),myPrevious=useMemo(()=>previous.filter(q=>Number(q.my_attempt_count||0)>0),[previous]),visiblePrevious=pastTab==="mine"?myPrevious:previous,topThree=ranking.slice(0,3),rest=ranking.slice(3);
 const register=async(id)=>{try{await registerLiveQuiz(id);setRegistrations(current=>({...current,[id]:true}));await load();}catch(e){console.error(e);}};
 const showPreviousStats=async(quiz)=>{try{const r=await getLiveQuizResult(quiz.id);setSelected(r.data.result);}catch(e){console.error(e);}};
 if(loading)return <StudentLayout><LoadingSpinner size="lg" className="py-20"/></StudentLayout>;
 return <StudentLayout><div className="min-w-0 space-y-8">
  <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-indigo-600">Live competitions</p><h1 className="page-title mt-1">Live Arena</h1><p className="page-subtitle">Scheduled contests, live results and your competition history.</p></div><Link to="/student/quizzes" className="btn-secondary">All quizzes <ArrowRight size={15}/></Link></header>
  {location.state?.completed&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-4"><p className="text-sm text-emerald-900">Live quiz completed</p><p className="mt-1 text-sm text-emerald-800">Rating earned: <span className="text-emerald-950">{Number(location.state.completed.rating||0).toFixed(2)}</span> · Event rank: <span className="text-emerald-950">#{location.state.completed.rank}</span></p></div>}
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="stat-card"><p className="text-xs text-slate-500">Live attended</p><p className="mt-2 text-2xl text-slate-900">{stats.attempted||0}</p></div><div className="stat-card"><p className="text-xs text-slate-500">Total rating</p><p className="mt-2 text-2xl text-slate-900">{Number(stats.rating||0).toFixed(2)}</p></div><div className="stat-card"><p className="text-xs text-slate-500">Global rank</p><p className="mt-2 text-2xl text-slate-900">#{stats.overall_rank||"—"}</p></div><div className="stat-card"><p className="text-xs text-slate-500">Upcoming</p><p className="mt-2 text-2xl text-slate-900">{upcoming.length}</p></div></section>
  {liveNow.length>0&&<section><div className="mb-4"><p className="eyebrow text-rose-600">Now</p><h2 className="mt-1 text-xl text-slate-950">Happening now</h2></div><div className="grid gap-4 lg:grid-cols-2">{liveNow.map(q=><article key={q.id} className="card border-rose-200"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-rose-50 px-2.5 py-1 text-[10px] uppercase tracking-wide text-rose-700">Live</span><span className="inline-flex items-center gap-1 text-xs text-slate-500"><Users size={14}/> {q.registration_count||0} registered</span></div><h3 className="mt-4 text-lg text-slate-900">{q.title}</h3><p className="mt-1 text-sm text-slate-500">{q.description||"Live quiz event"}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4 text-xs text-slate-500"><span>{q.question_count||0} questions</span><span className="inline-flex items-center gap-1"><Clock3 size={14}/> Live</span></div><button onClick={()=>navigate(`/student/live-quizzes/${q.id}/attempt`)} className="btn-primary mt-4 w-full">Enter live quiz <ArrowRight size={15}/></button></article>)}</div></section>}
  <section><div className="mb-4"><p className="eyebrow text-indigo-600">Scheduled</p><h2 className="mt-1 text-xl text-slate-950">Upcoming live quizzes</h2><p className="mt-1 text-sm text-slate-500">Register in advance and watch the countdown until the start.</p></div>{upcoming.length?<div className="grid gap-4 lg:grid-cols-2">{upcoming.map(q=><article key={q.id} className="card"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-[10px] uppercase tracking-wide text-indigo-700">Live quiz</span><h3 className="mt-3 text-lg text-slate-900">{q.title}</h3><p className="mt-1 text-sm text-slate-500">{q.description||"Scheduled competitive quiz challenge."}</p></div><div className="shrink-0 rounded-xl bg-slate-50 px-3 py-2 text-right"><p className="text-[10px] uppercase tracking-wide text-slate-400">Starts in</p><p className="mt-1 text-sm tabular-nums text-slate-900">{formatCountdown(q.live_start_at,now)}</p></div></div><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 border-t border-slate-100 pt-4 text-xs text-slate-500"><span>{formatDate(q.live_start_at)}</span><span>{q.question_count||0} questions</span><span>{q.registration_count||0} registered</span></div><div className="mt-4">{registrations[q.id]?<div className="rounded-xl bg-emerald-50 px-4 py-2.5 text-center text-sm text-emerald-700">Registered</div>:<button onClick={()=>register(q.id)} className="btn-primary w-full">Register in advance</button>}</div></article>)}</div>:<div className="card py-12 text-center text-sm text-slate-500">No upcoming live quizzes scheduled yet.</div>}</section>
  <section><div className="mb-4"><p className="eyebrow">Leaderboard</p><h2 className="mt-1 text-xl text-slate-950">Global live ranking</h2><p className="mt-1 text-sm text-slate-500">Overall position is calculated from completed live quiz ratings.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50/60 p-4 sm:p-6"><div className="grid gap-3 md:grid-cols-3 md:items-end">{topThree.map((item,i)=><div key={item.id} className={`rounded-2xl border bg-white p-5 text-center ${i===0?"border-indigo-200 md:-translate-y-3":"border-slate-200"}`}><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-slate-600"><Medal size={22}/></div><div className="mt-3 text-xs text-slate-400">#{item.rank}</div><div className="mt-1 flex justify-center"><Avatar user={item} size="h-14 w-14"/></div><p className="mt-3 truncate text-sm text-slate-900">{item.name}</p><p className="mt-1 text-lg tabular-nums text-slate-900">{Number(item.total_rating||0).toFixed(2)}</p><p className="text-xs text-slate-400">{item.attended} attended</p></div>)}</div>{rest.length>0&&<div className="mt-5 space-y-2">{rest.map(item=><RankRow key={item.id} item={item}/>)}</div>}</div></section>
  <section><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">History</p><h2 className="mt-1 text-xl text-slate-950">Past contests</h2><p className="mt-1 text-sm text-slate-500">Review finished events or only contests you attended.</p></div><div className="flex rounded-xl border border-slate-200 bg-white p-1"><button onClick={()=>setPastTab("all")} className={`rounded-lg px-3 py-2 text-xs ${pastTab==="all"?"bg-slate-100 text-slate-900":"text-slate-500"}`}>Past contests ({previous.length})</button><button onClick={()=>setPastTab("mine")} className={`rounded-lg px-3 py-2 text-xs ${pastTab==="mine"?"bg-slate-100 text-slate-900":"text-slate-500"}`}>My contests ({myPrevious.length})</button></div></div>{visiblePrevious.length?<div className="grid gap-4 md:grid-cols-2">{visiblePrevious.map(q=><PastContestCard key={q.id} quiz={q} onOpen={showPreviousStats}/>)}</div>:<div className="card py-12 text-center text-sm text-slate-500">No contests in this view yet.</div>}</section>
  {selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-3" onClick={()=>setSelected(null)}><div className="max-h-[92vh] w-full max-w-2xl overflow-auto rounded-2xl border border-slate-200 bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4 border-b border-slate-100 px-5 py-5 sm:px-7"><div><p className="eyebrow text-indigo-600">Event result</p><h2 className="mt-1 text-xl text-slate-950">{selected.title}</h2><p className="mt-1 text-sm text-slate-500">{formatDate(selected.live_start_at)}</p></div><button onClick={()=>setSelected(null)} className="btn-icon" aria-label="Close result"><X size={17}/></button></div><div className="space-y-6 px-5 py-5 sm:px-7 sm:py-7"><section><div className="mb-3"><h3 className="text-sm text-slate-900">Event overview</h3><p className="mt-1 text-xs text-slate-500">Final statistics for everyone who completed this live quiz.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><ResultMetric label="Questions" value={selected.question_count??0}/><ResultMetric label="Participants" value={selected.students??0} icon={Users}/><ResultMetric label="Attempts" value={selected.attempts??0}/><ResultMetric label="Average rating" value={Number(selected.avg_rating??0).toFixed(2)}/></div></section><section className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-sm text-slate-900">Your performance</h3><p className="mt-1 text-xs text-slate-500">Your final score and position in this event.</p></div>{selected.attempted&&<div className="rounded-xl bg-indigo-50 px-4 py-2 text-right"><p className="text-[10px] uppercase tracking-wide text-indigo-500">Event rating</p><p className="mt-1 text-xl tabular-nums text-indigo-700">{Number(selected.rating??0).toFixed(2)}</p></div>}</div>{selected.attempted?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5"><ResultMetric label="Rank" value={selected.rank?`#${selected.rank}`:"—"}/><ResultMetric label="Answered" value={selected.answered??0}/><ResultMetric label="Correct" value={selected.correct??0} tone="good" icon={CheckCircle2}/><ResultMetric label="Wrong" value={selected.wrong??0} tone="bad" icon={CircleX}/><ResultMetric label="Unanswered" value={selected.unanswered??0} tone="warn" icon={CircleHelp}/></div>:<div className="mt-4 rounded-xl bg-white px-4 py-5 text-center text-sm text-slate-500">You did not attend this contest.</div>}</section></div></div></div>}
 </div></StudentLayout>;
}
