import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import AdminLayout from "../../components/admin/AdminLayout";
import LoadingSpinner from "../../components/common/LoadingSpinner";
import { getLiveQuizzes, getLiveQuizStats, getAdminLiveQuizStats } from "../../api/liveQuiz.api";
import { publishLiveQuiz, unpublishLiveQuiz, deleteLiveQuiz } from "../../api/adminLiveQuiz.api";

const getStatus = (quiz) => {
  if (quiz.status === "draft") return "Draft";
  if (quiz.live_state === "live") return "Live now";
  if (quiz.live_state === "upcoming") return "Upcoming";
  return "Completed";
};
const displayIst = (value) => value ? String(value).replace("T", " ").slice(0, 16) : "—";

export default function LiveQuizManagement() {
  const [items, setItems] = useState([]), [stats, setStats] = useState({}), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(null);
  const load = async () => { try { const [listResponse, statsResponse] = await Promise.all([getLiveQuizzes(), getLiveQuizStats()]); setItems(listResponse.data.quizzes || []); setStats(statsResponse.data.stats || {}); } catch (error) { console.error(error); } finally { setLoading(false); } };
  useEffect(() => { load(); const timer = setInterval(load, 10000); return () => clearInterval(timer); }, []);
  const grouped = useMemo(() => ({ draft: items.filter((q) => getStatus(q) === "Draft"), live: items.filter((q) => getStatus(q) === "Live now"), upcoming: items.filter((q) => getStatus(q) === "Upcoming"), completed: items.filter((q) => getStatus(q) === "Completed") }), [items]);
  const togglePublish = async (quiz) => { setBusy(quiz.id); try { if (quiz.status === "published") await unpublishLiveQuiz(quiz.id); else await publishLiveQuiz(quiz.id); await load(); } catch (error) { alert(error?.response?.data?.message || "Unable to change live quiz status."); } finally { setBusy(null); } };
  const remove = async (quiz) => { if (!window.confirm(`Delete live quiz "${quiz.title}" permanently?`)) return; setBusy(quiz.id); try { await deleteLiveQuiz(quiz.id); await load(); } catch (error) { alert(error?.response?.data?.message || "Unable to delete live quiz."); } finally { setBusy(null); } };
  const openStats = async (quiz) => { try { const response = await getAdminLiveQuizStats(quiz.id); setSelected(response.data.stats); } catch (error) { alert(error?.response?.data?.message || "Unable to load statistics."); } };
  if (loading) return <AdminLayout><LoadingSpinner size="lg" className="py-20" /></AdminLayout>;
  return <AdminLayout><div className="min-w-0 space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold sm:text-3xl">Live Quizzes</h1><span className="rounded-full bg-rose-100 px-3 py-1 text-xs font-bold text-rose-700">🔴 LIVE CENTER</span></div><p className="mt-1 text-sm text-slate-500">Create, publish, edit, delete and analyse live events from this section only.</p></div><Link to="/admin/quizzes/create?live=1" className="btn-primary text-center">＋ Create Live Quiz</Link></header>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[["Created",stats.total??items.length,"text-indigo-600"],["Draft",stats.drafts??grouped.draft.length,"text-slate-600"],["Live now",stats.live_now??grouped.live.length,"text-rose-600"],["Upcoming",stats.upcoming??grouped.upcoming.length,"text-amber-600"],["Completed",stats.completed??grouped.completed.length,"text-emerald-600"]].map(([label,value,color])=><div className="card" key={label}><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-black ${color}`}>{value}</p></div>)}</div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-3"><div className="card"><p className="text-xs text-slate-500">Total live attempts</p><p className="mt-1 text-2xl font-bold">{stats.attempts||0}</p></div><div className="card"><p className="text-xs text-slate-500">Average live rating</p><p className="mt-1 text-2xl font-bold text-indigo-600">{Number(stats.avg_rating||0).toFixed(2)}</p></div><div className="card"><p className="text-xs text-slate-500">Events</p><p className="mt-1 text-2xl font-bold text-emerald-600">{items.length}</p></div></div>
    <section className="card overflow-hidden p-0"><div className="border-b p-4"><h2 className="text-xl font-bold">Live Event Management</h2><p className="text-sm text-slate-500">Normal quizzes never appear here, and live quizzes never appear in the normal quiz listing.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Quiz</th><th className="p-3">Domain</th><th className="p-3">Status</th><th className="p-3">Start (IST)</th><th className="p-3">Questions</th><th className="p-3">Attempts</th><th className="p-3">Controls</th></tr></thead><tbody>{items.map((quiz)=>{const status=getStatus(quiz);return <tr key={quiz.id} className="border-b last:border-0 hover:bg-slate-50"><td className="p-3 font-semibold"><div className="flex items-center gap-2">{quiz.title}<span className="rounded-full bg-rose-100 px-2 py-0.5 text-[10px] font-bold text-rose-700">LIVE QUIZ</span></div></td><td className="p-3">{quiz.live_all_domains?"All Domains":quiz.domain_name||"—"}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${status==="Live now"?"bg-rose-100 text-rose-700":status==="Upcoming"?"bg-amber-100 text-amber-700":status==="Completed"?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{status}</span></td><td className="p-3">{displayIst(quiz.live_start_at)} IST</td><td className="p-3">{quiz.question_count||0}</td><td className="p-3">{quiz.attempt_count||0}</td><td className="p-3"><div className="flex flex-wrap gap-2"><Link to={`/admin/live-quizzes/${quiz.id}`} className="btn-secondary text-xs">Manage</Link><Link to={`/admin/live-quizzes/${quiz.id}/edit`} className="btn-secondary text-xs">Edit</Link><button onClick={()=>openStats(quiz)} className="btn-secondary text-xs">Stats</button>{status!=="Live now"&&status!=="Completed"&&<button disabled={busy===quiz.id} onClick={()=>togglePublish(quiz)} className="btn-primary text-xs">{busy===quiz.id?"…":quiz.status==="published"?"Unpublish":"Publish"}</button>}{status!=="Live now"&&<button disabled={busy===quiz.id} onClick={()=>remove(quiz)} className="btn-secondary text-xs text-rose-600">Delete</button>}</div></td></tr>})}</tbody></table></div></section>
    {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-3" onClick={()=>setSelected(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-5 shadow-2xl sm:p-7" onClick={(e)=>e.stopPropagation()}><div className="flex justify-between gap-3"><div><span className="rounded-full bg-rose-100 px-2 py-1 text-[10px] font-bold text-rose-700">LIVE QUIZ</span><h2 className="mt-2 text-xl font-bold sm:text-2xl">{selected.title}</h2><p className="text-sm text-slate-500">Event analytics</p></div><button onClick={()=>setSelected(null)} className="h-9 w-9 rounded-full bg-slate-100">×</button></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Attempts",selected.attempts],["Registered",selected.registrations],["Students",selected.students],["Avg rating",selected.avg_rating],["Top rating",selected.top_rating]].map(([label,value])=><div key={label} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div><div className="mt-5 text-sm text-slate-600"><p>Start: {displayIst(selected.live_start_at)} IST</p><p>Automatic end: {displayIst(selected.computed_end_at)} IST</p></div></div></div>}
  </div></AdminLayout>;
}
