import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import { getQuizById, createQuiz, updateQuiz, getCategories } from "../../api/quiz.api";
import { getDomains } from "../../api/domain.api";
import AdminLayout from "../../components/admin/AdminLayout";
import LoadingSpinner from "../../components/common/LoadingSpinner";
import { getErrorMessage } from "../../utils/helpers";

const DEFAULT_SCORING={live_score_025:2,live_score_050:1.5,live_score_075:1.25,live_score_100:1,live_score_wrong:-0.5};

export default function QuizForm(){
 const{id}=useParams(),location=useLocation(),navigate=useNavigate(),isEdit=Boolean(id),createLive=new URLSearchParams(location.search).get("live")==="1";
 const[categories,setCategories]=useState([]),[domains,setDomains]=useState([]),[domainId,setDomainId]=useState(""),[loading,setLoading]=useState(isEdit),[error,setError]=useState("");
 const{register,handleSubmit,reset,setValue,watch,formState:{errors,isSubmitting}}=useForm({defaultValues:{difficulty:"medium",max_attempts:1,passing_score:60,duration:10,is_live_quiz:createLive,live_all_domains:false,...DEFAULT_SCORING}});
 const categoryId=watch("category_id"),isLive=watch("is_live_quiz"),allDomains=watch("live_all_domains");
 useEffect(()=>{Promise.all([getDomains(),getCategories(),isEdit?getQuizById(id):Promise.resolve(null)]).then(([dr,cr,qr])=>{const ds=dr.data.domains||[],cs=cr.data.categories||[];setDomains(ds);setCategories(cs);if(qr?.data?.quiz){const q=qr.data.quiz,cat=cs.find(c=>String(c.id)===String(q.category_id));setDomainId(q.live_all_domains?"all":String(q.domain_id??cat?.domain_id??""));reset({...q,category_id:q.category_id?String(q.category_id):"",is_live_quiz:Boolean(q.is_live_quiz),live_all_domains:Boolean(q.live_all_domains),live_score_025:Number(q.live_score_025??2),live_score_050:Number(q.live_score_050??1.5),live_score_075:Number(q.live_score_075??1.25),live_score_100:Number(q.live_score_100??1),live_score_wrong:Number(q.live_score_wrong??-0.5)});}else if(createLive){setDomainId("all");setValue("live_all_domains",true);}else if(ds[0])setDomainId(String(ds[0].id));}).catch(e=>setError(getErrorMessage(e))).finally(()=>setLoading(false));},[id,isEdit,reset,setValue,createLive]);
 const domainCategories=allDomains?categories:categories.filter(c=>String(c.domain_id)===String(domainId));
 useEffect(()=>{if(categoryId&&domainId!=="all"&&!domainCategories.some(c=>String(c.id)===String(categoryId)))setValue("category_id","");},[domainId,categoryId,setValue,allDomains,domainCategories]);
 const onSubmit=async(form)=>{setError("");try{if(isLive&&!form.live_start_at)return setError("Live quiz needs a start time in IST.");if(isLive&&!allDomains&&!form.category_id)return setError("Select a category or choose All Domains.");if(isLive){for(const[k,v]of Object.entries(DEFAULT_SCORING))if(form[k]===undefined||Number.isNaN(Number(form[k])))return setError("All live scoring values are required.");}
  const selected=domainCategories.find(c=>String(c.id)===String(form.category_id));const data={...form,domain_id:allDomains?"all":domainId,category_id:allDomains?null:(form.category_id||null),domain_name:allDomains?"All Domains":domains.find(d=>String(d.id)===String(domainId))?.name||null,category_name:selected?.name||"All Categories",is_live_quiz:Boolean(isLive),live_all_domains:Boolean(allDomains),live_end_at:null};if(isEdit)await updateQuiz(id,data);else await createQuiz(data);navigate(isLive?"/admin/live-quizzes":"/admin/quizzes");}catch(e){setError(getErrorMessage(e))}};
 if(loading)return <AdminLayout><LoadingSpinner size="lg" className="py-20"/></AdminLayout>;
 return <AdminLayout><div className="max-w-4xl mx-auto space-y-6 min-w-0"><div><Link to={isLive?"/admin/live-quizzes":"/admin/quizzes"} className="text-sm text-slate-500">← Back</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h2 className="text-2xl sm:text-3xl font-bold">{isLive?"Create Live Quiz":isEdit?"Edit Quiz":"Create Quiz"}</h2>{isLive&&<span className="rounded-full bg-rose-100 px-3 py-1 text-xs font-bold text-rose-700">🔴 LIVE QUIZ ONLY</span>}</div></div>
 {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
 <div className="card"><form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
  <div><label className="label">Title *</label><input className="input" {...register("title",{required:"Title is required"})}/>{errors.title&&<p className="text-rose-500 text-xs mt-1">{errors.title.message}</p>}</div>
  <div><label className="label">Description</label><textarea className="input" rows={4} {...register("description")}/></div>
  <div className="grid gap-4 md:grid-cols-2"><div><label className="label">Domain *</label><select className="input" value={domainId} onChange={e=>{const v=e.target.value;setDomainId(v);setValue("category_id","");setValue("live_all_domains",v==="all");}}><option value="">Select domain</option>{isLive&&<option value="all">🌐 All Domains</option>}{domains.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><p className="mt-1 text-xs text-slate-500">{domainId==="all"?"Visible to every student only in Live Quizzes.":"Students in the selected domain can see this event."}</p></div>
  <div><label className="label">Category {allDomains?"(not required)":"*"}</label><select className="input" {...register("category_id",{required:isLive&&!allDomains})} disabled={!domainId||(!allDomains&&!domainCategories.length)}><option value="">{allDomains?"Default / All Categories":!domainId?"Select domain first":!domainCategories.length?"No categories in this domain":"Select category"}</option>{domainCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div>
  {isLive&&<label className="flex items-center gap-3 rounded-2xl border border-indigo-100 bg-indigo-50/50 p-4"><input type="checkbox" className="h-5 w-5" checked={Boolean(allDomains)} onChange={e=>{const on=e.target.checked;setValue("live_all_domains",on);setDomainId(on?"all":domains[0]?.id?String(domains[0].id):"");setValue("category_id","");}}/><span><b className="text-indigo-900">🌐 All Domains</b><span className="block text-xs text-slate-500 mt-1">No category is required. This event is shown to every student only in Live Quizzes.</span></span></label>}
  <div><label className="label">Difficulty *</label><select className="input" {...register("difficulty",{required:true})}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></div>
  {!isLive&&<div className="grid gap-4 md:grid-cols-2"><div><label className="label">Overall Duration (min) *</label><input type="number" min="1" className="input" {...register("duration",{required:true,valueAsNumber:true})}/></div><div><label className="label">Passing Score (%) *</label><input type="number" min="1" max="100" className="input" {...register("passing_score",{required:true,valueAsNumber:true})}/></div><div><label className="label">Max Attempts</label><input type="number" min="1" className="input" {...register("max_attempts",{valueAsNumber:true})}/></div></div>}
  {isLive&&<>
   <div className="rounded-3xl border border-rose-200 bg-gradient-to-br from-rose-50 to-orange-50 p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-bold text-lg">🔴 Live Scoring Rules</h3><p className="text-xs text-slate-600 mt-1">These are the actual multipliers used by the backend. Set them before publishing.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-rose-700">Per correct answer</span></div><div className="mt-4 grid grid-cols-2 md:grid-cols-5 gap-3">{[["live_score_025","≤ 0.25× time","2.0×"],["live_score_050","≤ 0.50× time","1.5×"],["live_score_075","≤ 0.75× time","1.25×"],["live_score_100","≤ 1.00× time","1.0×"],["live_score_wrong","Wrong answer","-0.5×"]].map(([name,label,placeholder])=><div key={name}><label className="text-xs font-semibold text-slate-700">{label}</label><input type="number" step="0.05" className="input mt-1" placeholder={placeholder} {...register(name,{required:true,valueAsNumber:true})}/></div>)}</div><p className="mt-3 text-xs text-slate-500">Unanswered = 0×. Final rating = question marks × selected multiplier. Each question still has its own timer.</p></div>
   <div className="grid gap-4 md:grid-cols-2"><div><label className="label">Live Start Time (IST) *</label><input type="datetime-local" className="input" {...register("live_start_at",{required:true})}/><p className="mt-1 text-xs text-slate-500">The event starts automatically. No end time is required.</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><b className="text-amber-800">⏱ Individual question timers</b><p className="mt-1 text-xs text-amber-700">After creating the event, open Manage → Add Question. Every live question has a required 5–600 second timer.</p></div></div>
  </>}
  <div><label className="label">Thumbnail URL</label><input className="input" type="url" {...register("thumbnail_url")}/></div>
  <div className="flex flex-col gap-3 sm:flex-row sm:justify-end"><Link to={isLive?"/admin/live-quizzes":"/admin/quizzes"} className="btn-secondary text-center">Cancel</Link><button type="submit" disabled={isSubmitting||!domainId||(isLive&&!allDomains&&!categoryId)} className="btn-primary">{isSubmitting?"Saving…":isLive?(isEdit?"Update Live Quiz":"Create Live Quiz"):(isEdit?"Update Quiz":"Create Quiz")}</button></div>
 </form></div></div></AdminLayout>;
}
